name: Build Kivy APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: false

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y libncurses6 unzip zip openjdk-17-jdk \
          python3-pip python3-setuptools python3-wheel python3-dev git \
          autoconf libtool pkg-config
        pip install --upgrade pip
        pip install buildozer cython

    - name: Install Android SDK, Build-tools, NDK, and accept licenses
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d cmdline-tools-temp
        mkdir -p cmdline-tools/latest
        mv cmdline-tools-temp/cmdline-tools/* cmdline-tools/latest/
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk --licenses
        $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk \
          "platform-tools" "platforms;android-33" "build-tools;34.0.0" "ndk;27.2.12479018"

    - name: Configure git and fetch submodules with retry
      run: |
        git config --global http.postBuffer 524288000
        git config --global http.lowSpeedLimit 0
        git config --global http.lowSpeedTime 999999
        attempts=0
        until [ $attempts -ge 3 ]
        do
          git submodule update --init --recursive && break
          attempts=$((attempts+1))
          echo "Retrying submodule update ($attempts)..."
          sleep 5
        done

    - name: Prepare environment for autoreconf (if needed)
      run: |
        if [ -f configure.ac ]; then
          echo "Running autoupdate and autoreconf..."
          autoupdate || true
          autoreconf -i || true
        fi

    - name: Build APK
      env:
        ANDROIDSDK: $HOME/android-sdk
        ANDROIDNDK: $HOME/android-sdk/ndk/27.2.12479018
        ANDROIDAPI: 33
        ANDROIDMINAPI: 21
      run: |
        buildozer android clean
        buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: kivy-apk
        path: bin/*.apk
